service: halogen-backoffice-extract-script
frameworkVersion: ">=2.10.0 <3.0.0"

provider:
  name: aws
  runtime: nodejs18.x
  profile: extractFileProfile
  region: ap-southeast-1
  environment:
    bucketName: ${self:custom.bucketName}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:ListBucket
      Resource: arn:aws:s3:::backoffice-script
    - Effect: "Allow"
      Action:
        - s3:GetObject
        - s3:PutObject
        - s3:DeleteObject
      Resource: arn:aws:s3:::backoffice-script/*  

package:
  individually: true
  exclude:
    - serverless/**       

custom:
  customVariable1: Hello, World!
  bucketName: backoffice-script

functions:
  extractFiles:
    runtime: provided.al2023
    handler: ./bin/bootstrap
    events:
      - http:
          path: /extractFiles
          method: GET
    package:
      artifact: ./bin/bootstrap.zip